### ISSUE TITLE
Improve Promise types

### ISSUE THREAD

**Issue by Didas-git** [mxsdev/ts-type-explorer#18]
Currently one of the major problems is that Promises are shown as an object type and do not give you the return type upfront.
My idea would be to use the `<type arguments>` to defined the promise type since it contains the proper type of the promise.
![image](https://user-images.githubusercontent.com/80978939/201147544-acd7eeb2-9d32-474e-b65f-ccb73cb882a1.png)

Another issue is that promises show a rather useless tag when looking into them 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/80978939/201148040-ae4648f4-8668-442e-9e29-5e2ebe35a7d0.png">

**Comment by mxsdev** [comment]
This is really two issues: one for providing type arguments, and another for internal symbols - so I'm gonna break it into two.
