### ISSUE TITLE
Test Errors

### ISSUE THREAD

**Issue by Didas-git** [mxsdev/ts-type-explorer#28]
As of now running tests on the lib will always result in 2 errors.
This errors come from the `module.ts` file and are a result of how the tests are writen, i dont think this is a huge issue but at least one that should be mentioned on the contributing.md file.

Error:
![Screenshot 2022-11-14 at 10 31 32](https://user-images.githubusercontent.com/80978939/201638407-d2cf087d-4138-4a4d-95e9-4a4f78b5803f.png)

**Comment by mxsdev** [comment]
Fixed in 0c401dfc740962f329a419c88b29b074a25456d9
